
local atlas = "images/inventoryimageshamlet.xml"
AddRecipe("player_house_cottage_craft",     {}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_tudor_craft",       {}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_gothic_craft",      {}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_brick_craft",       {}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_turret_craft",      {}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_villa_craft",       {}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_manor_craft",       {}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)

AddRecipe("deco_chair_classic",         {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_classic_placer",   nil, true, nil, nil, atlas, "reno_chair_classic.tex")
AddRecipe("deco_chair_corner",          {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_corner_placer",    nil, true, nil, nil, atlas, "reno_chair_corner.tex")
AddRecipe("deco_chair_bench",           {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_bench_placer",     nil, true, nil, nil, atlas, "reno_chair_bench.tex")
AddRecipe("deco_chair_horned",          {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_horned_placer",    nil, true, nil, nil, atlas, "reno_chair_horned.tex")
AddRecipe("deco_chair_footrest",        {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_footrest_placer",  nil, true, nil, nil, atlas, "reno_chair_footrest.tex")
AddRecipe("deco_chair_lounge",          {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_lounge_placer",    nil, true, nil, nil, atlas, "reno_chair_lounge.tex")
AddRecipe("deco_chair_massager",        {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_massager_placer",  nil, true, nil, nil, atlas, "reno_chair_massager.tex")
AddRecipe("deco_chair_stuffed",         {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_stuffed_placer",   nil, true, nil, nil, atlas, "reno_chair_stuffed.tex")
AddRecipe("deco_chair_rocking",         {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_rocking_placer",   nil, true, nil, nil, atlas, "reno_chair_rocking.tex")
AddRecipe("deco_chair_ottoman",         {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "chair_ottoman_placer",   nil, true, nil, nil, atlas, "reno_chair_ottoman.tex")

AddRecipe("shelves_wood",               {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_wood_placer",           nil, true, nil, nil, atlas, "reno_shelves_wood.tex")
AddRecipe("shelves_basic",              {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_basic_placer",          nil, true, nil, nil, atlas, "reno_shelves_basic.tex")
AddRecipe("shelves_cinderblocks",       {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_cinderblocks_placer",   nil, true, nil, nil, atlas, "reno_shelves_cinderblocks.tex")
AddRecipe("shelves_marble",             {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_marble_placer",         nil, true, nil, nil, atlas, "reno_shelves_marble.tex")
AddRecipe("shelves_glass",              {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_glass_placer",          nil, true, nil, nil, atlas, "reno_shelves_glass.tex")
AddRecipe("shelves_ladder",             {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_ladder_placer",         nil, true, nil, nil, atlas, "reno_shelves_ladder.tex")
AddRecipe("shelves_hutch",              {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_hutch_placer",          nil, true, nil, nil, atlas, "reno_shelves_hutch.tex")
AddRecipe("shelves_industrial",         {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_industrial_placer",     nil, true, nil, nil, atlas, "reno_shelves_industrial.tex")
AddRecipe("shelves_adjustable",         {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_adjustable_placer",     nil, true, nil, nil, atlas, "reno_shelves_adjustable.tex")
AddRecipe("shelves_midcentury",         {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_midcentury_placer",     nil, true, nil, nil, atlas, "reno_shelves_midcentury.tex")
AddRecipe("shelves_wallmount",          {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_wallmount_placer",      nil, true, nil, nil, atlas, "reno_shelves_wallmount.tex")
AddRecipe("shelves_aframe",             {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_aframe_placer",         nil, true, nil, nil, atlas, "reno_shelves_aframe.tex")
AddRecipe("shelves_crates",             {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_crates_placer",         nil, true, nil, nil, atlas, "reno_shelves_crates.tex")
AddRecipe("shelves_fridge",             {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_fridge_placer",         nil, true, nil, nil, atlas, "reno_shelves_fridge.tex")
AddRecipe("shelves_floating",           {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_floating_placer",       nil, true, nil, nil, atlas, "reno_shelves_floating.tex")
AddRecipe("shelves_pipe",               {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_pipe_placer",           nil, true, nil, nil, atlas, "reno_shelves_pipe.tex")
AddRecipe("shelves_hattree",            {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_hattree_placer",        nil, true, nil, nil, atlas, "reno_shelves_hattree.tex")
AddRecipe("shelves_pallet",             {},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "shelves_pallet_placer",         nil, true, nil, nil, atlas, "reno_shelves_pallet.tex")

AddRecipe("rug_round",          {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_round_placer",     nil, true, nil, nil, atlas, "reno_rug_round.tex")
AddRecipe("rug_square",         {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_square_placer",    nil, true, nil, nil, atlas, "reno_rug_square.tex")
AddRecipe("rug_oval",           {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_oval_placer",      nil, true, nil, nil, atlas, "reno_rug_oval.tex")
AddRecipe("rug_rectangle",      {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_rectangle_placer", nil, true, nil, nil, atlas, "reno_rug_rectangle.tex")
AddRecipe("rug_fur",            {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_fur_placer",       nil, true, nil, nil, atlas, "reno_rug_fur.tex")
AddRecipe("rug_hedgehog",       {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_hedgehog_placer",  nil, true, nil, nil, atlas, "reno_rug_hedgehog.tex")
AddRecipe("rug_porcupuss",      {},            GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_porcupuss_placer", nil, true, nil, nil, atlas, "reno_rug_porcupuss.tex")
AddRecipe("rug_hoofprint",      {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_hoofprint_placer", nil, true, nil, nil, atlas, "reno_rug_hoofprint.tex")
AddRecipe("rug_octagon",        {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_octagon_placer",   nil, true, nil, nil, atlas, "reno_rug_octagon.tex")
AddRecipe("rug_swirl",          {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_swirl_placer",     nil, true, nil, nil, atlas, "reno_rug_swirl.tex")
AddRecipe("rug_catcoon",        {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_catcoon_placer",   nil, true, nil, nil, atlas, "reno_rug_catcoon.tex")
AddRecipe("rug_rubbermat",      {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_rubbermat_placer", nil, true, nil, nil, atlas, "reno_rug_rubbermat.tex")
AddRecipe("rug_web",            {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_web_placer",       nil, true, nil, nil, atlas, "reno_rug_web.tex")
AddRecipe("rug_metal",          {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_metal_placer",     nil, true, nil, nil, atlas, "reno_rug_metal.tex")
AddRecipe("rug_wormhole",       {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_wormhole_placer",  nil, true, nil, nil, atlas, "reno_rug_wormhole.tex")
AddRecipe("rug_braid",          {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_braid_placer",     nil, true, nil, nil, atlas, "reno_rug_braid.tex")
AddRecipe("rug_beard",          {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_beard_placer",     nil, true, nil, nil, atlas, "reno_rug_beard.tex")
AddRecipe("rug_nailbed",        {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_nailbed_placer",   nil, true, nil, nil, atlas, "reno_rug_nailbed.tex")
AddRecipe("rug_crime",          {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_crime_placer",     nil, true, nil, nil, atlas, "reno_rug_crime.tex")
AddRecipe("rug_tiles",          {},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "rug_tiles_placer",     nil, true, nil, nil, atlas, "reno_rug_tiles.tex")

AddRecipe("deco_chaise",                {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_chaise_placer", nil, true, nil, nil, atlas, "reno_chair_chaise.tex")

AddRecipe("deco_lamp_fringe",        {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_fringe_placer",         nil, true, nil, nil, atlas, "reno_lamp_fringe.tex")
AddRecipe("deco_lamp_stainglass",    {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_stainglass_placer",     nil, true, nil, nil, atlas, "reno_lamp_stainglass.tex")
AddRecipe("deco_lamp_downbridge",    {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_downbridge_placer",     nil, true, nil, nil, atlas, "reno_lamp_downbridge.tex")
AddRecipe("deco_lamp_2embroidered",  {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_2embroidered_placer",   nil, true, nil, nil, atlas, "reno_lamp_2embroidered.tex")
AddRecipe("deco_lamp_ceramic",       {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_ceramic_placer",        nil, true, nil, nil, atlas, "reno_lamp_ceramic.tex")
AddRecipe("deco_lamp_glass",         {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_glass_placer",          nil, true, nil, nil, atlas, "reno_lamp_glass.tex")
AddRecipe("deco_lamp_2fringes",      {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_2fringes_placer",       nil, true, nil, nil, atlas, "reno_lamp_2fringes.tex")
AddRecipe("deco_lamp_candelabra",    {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_candelabra_placer",     nil, true, nil, nil, atlas, "reno_lamp_candelabra.tex")
AddRecipe("deco_lamp_elizabethan",   {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_elizabethan_placer",    nil, true, nil, nil, atlas, "reno_lamp_elizabethan.tex")
AddRecipe("deco_lamp_gothic",        {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_gothic_placer",         nil, true, nil, nil, atlas, "reno_lamp_gothic.tex")
AddRecipe("deco_lamp_orb",           {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_orb_placer",            nil, true, nil, nil, atlas, "reno_lamp_orb.tex")
AddRecipe("deco_lamp_bellshade",     {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_bellshade_placer",      nil, true, nil, nil, atlas, "reno_lamp_bellshade.tex")
AddRecipe("deco_lamp_crystals",      {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_crystals_placer",       nil, true, nil, nil, atlas, "reno_lamp_crystals.tex")
AddRecipe("deco_lamp_upturn",        {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_upturn_placer",         nil, true, nil, nil, atlas, "reno_lamp_upturn.tex")
AddRecipe("deco_lamp_2upturns",      {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_2upturns_placer",       nil, true, nil, nil, atlas, "reno_lamp_2upturns.tex")
AddRecipe("deco_lamp_spool",         {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_spool_placer",          nil, true, nil, nil, atlas, "reno_lamp_spool.tex")
AddRecipe("deco_lamp_edison",        {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_edison_placer",         nil, true, nil, nil, atlas, "reno_lamp_edison.tex")
AddRecipe("deco_lamp_adjustable",    {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_adjustable_placer",     nil, true, nil, nil, atlas, "reno_lamp_adjustable.tex")
AddRecipe("deco_lamp_rightangles",   {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_rightangles_placer",    nil, true, nil, nil, atlas, "reno_lamp_rightangles.tex")
AddRecipe("deco_lamp_hoofspa",        {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_lamp_hoofspa_placer",        nil, true, nil, nil, atlas, "reno_lamp_hoofspa.tex")

AddRecipe("deco_plantholder_basic",        {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_basic_placer",           nil, true, nil, nil, atlas, "reno_plantholder_basic.tex")
AddRecipe("deco_plantholder_wip",          {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_wip_placer",             nil, true, nil, nil, atlas, "reno_plantholder_wip.tex")
AddRecipe("deco_plantholder_marble",        {}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_marble_placer",          nil, true, nil, nil, atlas, "reno_plantholder_marble.tex")
AddRecipe("deco_plantholder_bonsai",       {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_bonsai_placer",          nil, true, nil, nil, atlas, "reno_plantholder_bonsai.tex")
AddRecipe("deco_plantholder_dishgarden",   {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_dishgarden_placer",      nil, true, nil, nil, atlas, "reno_plantholder_dishgarden.tex")
AddRecipe("deco_plantholder_philodendron", {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_philodendron_placer",    nil, true, nil, nil, atlas, "reno_plantholder_philodendron.tex")
AddRecipe("deco_plantholder_orchid",       {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_orchid_placer",          nil, true, nil, nil, atlas, "reno_plantholder_orchid.tex")
AddRecipe("deco_plantholder_draceana",     {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_draceana_placer",        nil, true, nil, nil, atlas, "reno_plantholder_draceana.tex")
AddRecipe("deco_plantholder_xerographica", {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_xerographica_placer",    nil, true, nil, nil, atlas, "reno_plantholder_xerographica.tex")
AddRecipe("deco_plantholder_birdcage",     {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_birdcage_placer",        nil, true, nil, nil, atlas, "reno_plantholder_birdcage.tex")
AddRecipe("deco_plantholder_palm",         {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_palm_placer",            nil, true, nil, nil, atlas, "reno_plantholder_palm.tex")
AddRecipe("deco_plantholder_zz",           {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_zz_placer",              nil, true, nil, nil, atlas, "reno_plantholder_zz.tex")
AddRecipe("deco_plantholder_fernstand",    {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_fernstand_placer",       nil, true, nil, nil, atlas, "reno_plantholder_fernstand.tex")
AddRecipe("deco_plantholder_fern",         {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_fern_placer",            nil, true, nil, nil, atlas, "reno_plantholder_fern.tex")
AddRecipe("deco_plantholder_terrarium",    {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_terrarium_placer",       nil, true, nil, nil, atlas, "reno_plantholder_terrarium.tex")
AddRecipe("deco_plantholder_plantpet",     {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_plantpet_placer",        nil, true, nil, nil, atlas, "reno_plantholder_plantpet.tex")
AddRecipe("deco_plantholder_traps",        {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_traps_placer",           nil, true, nil, nil, atlas, "reno_plantholder_traps.tex")
AddRecipe("deco_plantholder_pitchers",     {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_pitchers_placer",        nil, true, nil, nil, atlas, "reno_plantholder_pitchers.tex")


AddRecipe("deco_plantholder_winterfeasttreeofsadness",      {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_winterfeasttreeofsadness_placer", nil, true, nil, nil, atlas, "reno_plantholder_winterfeasttreeofsadness.tex")
AddRecipe("deco_plantholder_winterfeasttree",              {},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_plantholder_winterfeasttree_placer",            nil, true, nil, nil, atlas, "reno_lamp_festivetree.tex") 

AddRecipe("deco_table_round",           {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_table_round_placer",    nil, true, nil, nil, atlas, "reno_table_round.tex")
AddRecipe("deco_table_banker",          {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_table_banker_placer",   nil, true, nil, nil, atlas, "reno_table_banker.tex")
AddRecipe("deco_table_diy",             {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_table_diy_placer",      nil, true, nil, nil, atlas, "reno_table_diy.tex")
AddRecipe("deco_table_raw",             {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_table_raw_placer",      nil, true, nil, nil, atlas, "reno_table_raw.tex")
AddRecipe("deco_table_crate",           {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_table_crate_placer",    nil, true, nil, nil, atlas, "reno_table_crate.tex")
AddRecipe("deco_table_chess",           {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_table_chess_placer",    nil, true, nil, nil, atlas, "reno_table_chess.tex")

AddRecipe("deco_wallornament_photo",                {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_photo_placer",               nil, true, nil, nil, atlas, "reno_wallornament_photo.tex")
AddRecipe("deco_wallornament_embroidery_hoop",      {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_embroidery_hoop_placer",     nil, true, nil, nil, atlas, "reno_wallornament_embroidery_hoop.tex")
AddRecipe("deco_wallornament_mosaic",               {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_mosaic_placer",              nil, true, nil, nil, atlas, "reno_wallornament_mosaic.tex")
AddRecipe("deco_wallornament_wreath",               {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_wreath_placer",              nil, true, nil, nil, atlas, "reno_wallornament_wreath.tex")
AddRecipe("deco_wallornament_axe",                  {Ingredient("goldnugget",1),  Ingredient("axe",1)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_axe_placer",                 nil, true, nil, nil, atlas, "reno_wallornament_axe.tex")
AddRecipe("deco_wallornament_hunt",                 {Ingredient("goldnugget",1),  Ingredient("spear",1)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_hunt_placer",                nil, true, nil, nil, atlas, "reno_wallornament_hunt.tex")
AddRecipe("deco_wallornament_periodic_table",       {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_periodic_table_placer",      nil, true, nil, nil, atlas, "reno_wallornament_periodic_table.tex")
AddRecipe("deco_wallornament_gears_art",            {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_gears_art_placer",           nil, true, nil, nil, atlas, "reno_wallornament_gears_art.tex")
AddRecipe("deco_wallornament_cape",                 {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_cape_placer",                nil, true, nil, nil, atlas, "reno_wallornament_cape.tex")
AddRecipe("deco_wallornament_no_smoking",           {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_no_smoking_placer",          nil, true, nil, nil, atlas, "reno_wallornament_no_smoking.tex")
AddRecipe("deco_wallornament_black_cat",            {},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wallornament_black_cat_placer",           nil, true, nil, nil, atlas, "reno_wallornament_black_cat.tex")
AddRecipe("deco_antiquities_wallfish",              {Ingredient("goldnugget",1),  Ingredient("fish",1)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_antiquities_wallfish_placer",             nil, true, nil, nil, atlas, "reno_antiquities_wallfish.tex")
AddRecipe("deco_antiquities_beefalo",               {Ingredient("goldnugget",1), Ingredient("horn",1)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_antiquities_beefalo_placer",              nil, true, nil, nil, atlas, "reno_antiquities_beefalo.tex")

AddRecipe("window_small_peaked_curtain",        {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "window_small_peaked_curtain_placer",    nil, true, nil, nil, atlas, "reno_window_small_peaked_curtain.tex")
AddRecipe("window_round_burlap",                {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "window_round_burlap_placer",            nil, true, nil, nil, atlas, "reno_window_round_burlap.tex")
AddRecipe("window_small_peaked",                {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "window_small_peaked_placer",            nil, true, nil, nil, atlas, "reno_window_small_peaked.tex")
AddRecipe("window_large_square",                {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "window_large_square_placer",            nil, true, nil, nil, atlas, "reno_window_large_square.tex")
AddRecipe("window_tall",                        {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "window_tall_placer",                    nil, true, nil, nil, atlas, "reno_window_tall.tex")
AddRecipe("window_large_square_curtain",        {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "window_large_square_curtain_placer",    nil, true, nil, nil, atlas, "reno_window_large_square_curtain.tex")
AddRecipe("window_tall_curtain",                {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "window_tall_curtain_placer",            nil, true, nil, nil, atlas, "reno_window_tall_curtain.tex")

AddRecipe("window_greenhouse",                  {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "window_greenhouse_placer",          nil, true, nil, nil, atlas, "reno_window_greenhouse.tex")

AddRecipe("deco_wood",                          {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_wood_cornerbeam_placer",       nil, true, nil, nil, atlas, "reno_cornerbeam_wood.tex")
AddRecipe("deco_millinery",                     {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_millinery_cornerbeam_placer",  nil, true, nil, nil, atlas, "reno_cornerbeam_millinery.tex")
AddRecipe("deco_round",                         {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_round_cornerbeam_placer",      nil, true, nil, nil, atlas, "reno_cornerbeam_round.tex")
AddRecipe("deco_marble",                        {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "deco_marble_cornerbeam_placer",     nil, true, nil, nil, atlas, "reno_cornerbeam_marble.tex")

AddRecipe("interior_floor_wood",                {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_marble",              {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_check",               {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_plaid_tile",          {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_sheet_metal",         {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
--[[ we dont have the anim for these                                                                                                                                                     
-- AddRecipe("interior_floor_gardenstone",         {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
-- AddRecipe("interior_floor_geometrictiles",      {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
-- AddRecipe("interior_floor_shag_carpet",         {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
-- AddRecipe("interior_floor_transitional",        {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
-- AddRecipe("interior_floor_woodpanels",          {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
--]]
AddRecipe("interior_floor_herringbone",         {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_hexagon",             {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_hoof_curvy",          {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_octagon",             {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
                                                                                                                                                     
AddRecipe("interior_wall_wood",                 {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_checkered",            {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_floral",               {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_sunflower",            {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_harlequin",            {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
--[[ we dont have the anim for these                                                                                                                                                   
AddRecipe("interior_wall_peagawk",              {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_plain_ds",             {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_plain_rog",            {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_rope",                 {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
--]]
AddRecipe("interior_wall_circles",              {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_marble",               {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_mayorsoffice",         {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_fullwall_moulding",    {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_upholstered",          {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)

AddRecipe("swinging_light_basic_bulb",          {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_basic_bulb_placer",            nil, true, nil, nil, atlas, "reno_light_basic_bulb.tex")
AddRecipe("swinging_light_basic_metal",         {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_basic_metal_placer",           nil, true, nil, nil, atlas, "reno_light_basic_metal.tex")
AddRecipe("swinging_light_chandalier_candles",  {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_chandalier_candles_placer",    nil, true, nil, nil, atlas, "reno_light_chandalier_candles.tex")
AddRecipe("swinging_light_rope_1",              {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_rope_1_placer",                nil, true, nil, nil, atlas, "reno_light_rope_1.tex")
AddRecipe("swinging_light_rope_2",              {},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_rope_2_placer",                nil, true, nil, nil, atlas, "reno_light_rope_2.tex")
AddRecipe("swinging_light_floral_bulb",         {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_floral_bulb_placer",           nil, true, nil, nil, atlas, "reno_light_floral_bulb.tex")
AddRecipe("swinging_light_pendant_cherries",    {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_pendant_cherries_placer",      nil, true, nil, nil, atlas, "reno_light_pendant_cherries.tex")
AddRecipe("swinging_light_floral_scallop",      {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_floral_scallop_placer",        nil, true, nil, nil, atlas, "reno_light_floral_scallop.tex")
AddRecipe("swinging_light_floral_bloomer",      {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_floral_bloomer_placer",        nil, true, nil, nil, atlas, "reno_light_floral_bloomer.tex")
AddRecipe("swinging_light_tophat",              {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_tophat_placer",                nil, true, nil, nil, atlas, "reno_light_tophat.tex")
AddRecipe("swinging_light_derby",               {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "swinging_light_derby_placer",                 nil, true, nil, nil, atlas, "reno_light_derby.tex")

-- DOORS
        --name,         ingredients,                tab,                    level,          game_type,                  placer,       min_spacing, nounlock, numtogive, aquatic, distance, decor, flipable, image, wallitem
AddRecipe("wood_door",      {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "wood_door_placer",    nil, true, nil, nil, atlas, "wood_door.tex")
AddRecipe("stone_door",     {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "stone_door_placer",   nil, true, nil, nil, atlas, "stone_door.tex")
AddRecipe("organic_door",   {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "organic_door_placer", nil, true, nil, nil, atlas, "organic_door.tex")
AddRecipe("iron_door",      {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "iron_door_placer",    nil, true, nil, nil, atlas, "iron_door.tex")
AddRecipe("curtain_door",   {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "curtain_door_placer", nil, true, nil, nil, atlas, "curtain_door.tex")
AddRecipe("plate_door",     {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "plate_door_placer",   nil, true, nil, nil, atlas, "plate_door.tex")
AddRecipe("round_door",     {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "round_door_placer",   nil, true, nil, nil, atlas, "round_door.tex")
AddRecipe("pillar_door",    {},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, "pillar_door_placer",  nil, true, nil, nil, atlas, "pillar_door.tex")

AddRecipe("construction_permit",   {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
AddRecipe("demolition_permit",     {},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.NONE, nil, nil, true,nil,nil,atlas)
