


-- DST:
-- name, ingredients, tab, level, placer, min_spacing, nounlock, numtogive, builder_tag, atlas, image, testfn, product, build_mode, build_distance
-- name, ingredients, tab, level, placer, min_spacing, nounlock, numtogive, aquatic, distance, decor, flipable, image, wallitem, alt_ingredients
-- aquatic und distance kann weg , auch ist dies kein decor (vierter/fünfter eintrag nnach placer)
-- decor ist bei allen true, außer player_house.., wall/floor und permit -> soweit ich sehe dorgt dies dafür, dass es überall gebaut werden kann, egal ob eine anderes structure blockt.
-- -> code dazu ist in builder replica CanBuildAtPoint , welches aktuell nur die map.CanDeployRecipeAtPoint fkt prüft, welche wiederum auch die recipe.testfn prüft
-- nur die testfn kann alleine das ergebnis nicht true machen, nur false. Erstmal testen welche beschränkungen die dekos beim bauen haben und evlt hier dann reinhooken
-- also testen ob: deko auf structue und strucutre auf deco baubar ist.
-- flipable erstmal weglassen, ist letzter eintrag vor image string
-- wallitem hat weniger wirkung als gedacht, alles was kein wallitem ist kann nicht direkt an der wand gebaut werden, ansonten keine wirkung, daher erstmal weglassen.
-- wallitems sind alle shelves, ornament, fesnter, cornerbeam und door.
-- alt_ingredients wird scheinbar nicht verwendet


local atlas = "images/inventoryimageshamlet.xml"
AddRecipe("player_house_cottage_craft",     {Ingredient("goldnugget",10)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_tudor_craft",       {Ingredient("goldnugget",10)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_gothic_craft",      {Ingredient("goldnugget",10)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_brick_craft",       {Ingredient("goldnugget",10)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_turret_craft",      {Ingredient("goldnugget",10)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_villa_craft",       {Ingredient("goldnugget",30)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("player_house_manor_craft",       {Ingredient("goldnugget",30)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)

AddRecipe("deco_chair_classic",         {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_classic_placer",   nil, true, nil, nil, atlas, "reno_chair_classic.tex")
AddRecipe("deco_chair_corner",          {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_corner_placer",    nil, true, nil, nil, atlas, "reno_chair_corner.tex")
AddRecipe("deco_chair_bench",           {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_bench_placer",     nil, true, nil, nil, atlas, "reno_chair_bench.tex")
AddRecipe("deco_chair_horned",          {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_horned_placer",    nil, true, nil, nil, atlas, "reno_chair_horned.tex")
AddRecipe("deco_chair_footrest",        {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_footrest_placer",  nil, true, nil, nil, atlas, "reno_chair_footrest.tex")
AddRecipe("deco_chair_lounge",          {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_lounge_placer",    nil, true, nil, nil, atlas, "reno_chair_lounge.tex")
AddRecipe("deco_chair_massager",        {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_massager_placer",  nil, true, nil, nil, atlas, "reno_chair_massager.tex")
AddRecipe("deco_chair_stuffed",         {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_stuffed_placer",   nil, true, nil, nil, atlas, "reno_chair_stuffed.tex")
AddRecipe("deco_chair_rocking",         {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_rocking_placer",   nil, true, nil, nil, atlas, "reno_chair_rocking.tex")
AddRecipe("deco_chair_ottoman",         {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "chair_ottoman_placer",   nil, true, nil, nil, atlas, "reno_chair_ottoman.tex")

AddRecipe("shelves_wood",               {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_wood_placer",           nil, true, nil, nil, atlas, "reno_shelves_wood.tex")
AddRecipe("shelves_basic",              {Ingredient("goldnugget",2)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_basic_placer",          nil, true, nil, nil, atlas, "reno_shelves_basic.tex")
AddRecipe("shelves_cinderblocks",       {Ingredient("goldnugget",1)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_cinderblocks_placer",   nil, true, nil, nil, atlas, "reno_shelves_cinderblocks.tex")
AddRecipe("shelves_marble",             {Ingredient("goldnugget",8)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_marble_placer",         nil, true, nil, nil, atlas, "reno_shelves_marble.tex")
AddRecipe("shelves_glass",              {Ingredient("goldnugget",8)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_glass_placer",          nil, true, nil, nil, atlas, "reno_shelves_glass.tex")
AddRecipe("shelves_ladder",             {Ingredient("goldnugget",8)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_ladder_placer",         nil, true, nil, nil, atlas, "reno_shelves_ladder.tex")
AddRecipe("shelves_hutch",              {Ingredient("goldnugget",8)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_hutch_placer",          nil, true, nil, nil, atlas, "reno_shelves_hutch.tex")
AddRecipe("shelves_industrial",         {Ingredient("goldnugget",8)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_industrial_placer",     nil, true, nil, nil, atlas, "reno_shelves_industrial.tex")
AddRecipe("shelves_adjustable",         {Ingredient("goldnugget",8)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_adjustable_placer",     nil, true, nil, nil, atlas, "reno_shelves_adjustable.tex")
AddRecipe("shelves_midcentury",         {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_midcentury_placer",     nil, true, nil, nil, atlas, "reno_shelves_midcentury.tex")
AddRecipe("shelves_wallmount",          {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_wallmount_placer",      nil, true, nil, nil, atlas, "reno_shelves_wallmount.tex")
AddRecipe("shelves_aframe",             {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_aframe_placer",         nil, true, nil, nil, atlas, "reno_shelves_aframe.tex")
AddRecipe("shelves_crates",             {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_crates_placer",         nil, true, nil, nil, atlas, "reno_shelves_crates.tex")
AddRecipe("shelves_fridge",             {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_fridge_placer",         nil, true, nil, nil, atlas, "reno_shelves_fridge.tex")
AddRecipe("shelves_floating",           {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_floating_placer",       nil, true, nil, nil, atlas, "reno_shelves_floating.tex")
AddRecipe("shelves_pipe",               {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_pipe_placer",           nil, true, nil, nil, atlas, "reno_shelves_pipe.tex")
AddRecipe("shelves_hattree",            {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_hattree_placer",        nil, true, nil, nil, atlas, "reno_shelves_hattree.tex")
AddRecipe("shelves_pallet",             {Ingredient("goldnugget",6)},         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "shelves_pallet_placer",         nil, true, nil, nil, atlas, "reno_shelves_pallet.tex")

AddRecipe("rug_round",          {Ingredient("goldnugget",2)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_round_placer",     nil, true, nil, nil, atlas, "reno_rug_round.tex")
AddRecipe("rug_square",         {Ingredient("goldnugget",2)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_square_placer",    nil, true, nil, nil, atlas, "reno_rug_square.tex")
AddRecipe("rug_oval",           {Ingredient("goldnugget",2)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_oval_placer",      nil, true, nil, nil, atlas, "reno_rug_oval.tex")
AddRecipe("rug_rectangle",      {Ingredient("goldnugget",3)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_rectangle_placer", nil, true, nil, nil, atlas, "reno_rug_rectangle.tex")
AddRecipe("rug_fur",            {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_fur_placer",       nil, true, nil, nil, atlas, "reno_rug_fur.tex")
AddRecipe("rug_hedgehog",       {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_hedgehog_placer",  nil, true, nil, nil, atlas, "reno_rug_hedgehog.tex")
AddRecipe("rug_porcupuss",      {Ingredient("goldnugget",10)},            GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_porcupuss_placer", nil, true, nil, nil, atlas, "reno_rug_porcupuss.tex")
AddRecipe("rug_hoofprint",      {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_hoofprint_placer", nil, true, nil, nil, atlas, "reno_rug_hoofprint.tex")
AddRecipe("rug_octagon",        {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_octagon_placer",   nil, true, nil, nil, atlas, "reno_rug_octagon.tex")
AddRecipe("rug_swirl",          {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_swirl_placer",     nil, true, nil, nil, atlas, "reno_rug_swirl.tex")
AddRecipe("rug_catcoon",        {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_catcoon_placer",   nil, true, nil, nil, atlas, "reno_rug_catcoon.tex")
AddRecipe("rug_rubbermat",      {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_rubbermat_placer", nil, true, nil, nil, atlas, "reno_rug_rubbermat.tex")
AddRecipe("rug_web",            {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_web_placer",       nil, true, nil, nil, atlas, "reno_rug_web.tex")
AddRecipe("rug_metal",          {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_metal_placer",     nil, true, nil, nil, atlas, "reno_rug_metal.tex")
AddRecipe("rug_wormhole",       {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_wormhole_placer",  nil, true, nil, nil, atlas, "reno_rug_wormhole.tex")
AddRecipe("rug_braid",          {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_braid_placer",     nil, true, nil, nil, atlas, "reno_rug_braid.tex")
AddRecipe("rug_beard",          {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_beard_placer",     nil, true, nil, nil, atlas, "reno_rug_beard.tex")
AddRecipe("rug_nailbed",        {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_nailbed_placer",   nil, true, nil, nil, atlas, "reno_rug_nailbed.tex")
AddRecipe("rug_crime",          {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_crime_placer",     nil, true, nil, nil, atlas, "reno_rug_crime.tex")
AddRecipe("rug_tiles",          {Ingredient("goldnugget",5)},             GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "rug_tiles_placer",     nil, true, nil, nil, atlas, "reno_rug_tiles.tex")

AddRecipe("deco_chaise",                {Ingredient("goldnugget",15)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_chaise_placer", nil, true, nil, nil, atlas, "reno_chair_chaise.tex")

AddRecipe("deco_lamp_fringe",        {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_fringe_placer",         nil, true, nil, nil, atlas, "reno_lamp_fringe.tex")
AddRecipe("deco_lamp_stainglass",    {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_stainglass_placer",     nil, true, nil, nil, atlas, "reno_lamp_stainglass.tex")
AddRecipe("deco_lamp_downbridge",    {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_downbridge_placer",     nil, true, nil, nil, atlas, "reno_lamp_downbridge.tex")
AddRecipe("deco_lamp_2embroidered",  {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_2embroidered_placer",   nil, true, nil, nil, atlas, "reno_lamp_2embroidered.tex")
AddRecipe("deco_lamp_ceramic",       {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_ceramic_placer",        nil, true, nil, nil, atlas, "reno_lamp_ceramic.tex")
AddRecipe("deco_lamp_glass",         {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_glass_placer",          nil, true, nil, nil, atlas, "reno_lamp_glass.tex")
AddRecipe("deco_lamp_2fringes",      {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_2fringes_placer",       nil, true, nil, nil, atlas, "reno_lamp_2fringes.tex")
AddRecipe("deco_lamp_candelabra",    {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_candelabra_placer",     nil, true, nil, nil, atlas, "reno_lamp_candelabra.tex")
AddRecipe("deco_lamp_elizabethan",   {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_elizabethan_placer",    nil, true, nil, nil, atlas, "reno_lamp_elizabethan.tex")
AddRecipe("deco_lamp_gothic",        {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_gothic_placer",         nil, true, nil, nil, atlas, "reno_lamp_gothic.tex")
AddRecipe("deco_lamp_orb",           {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_orb_placer",            nil, true, nil, nil, atlas, "reno_lamp_orb.tex")
AddRecipe("deco_lamp_bellshade",     {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_bellshade_placer",      nil, true, nil, nil, atlas, "reno_lamp_bellshade.tex")
AddRecipe("deco_lamp_crystals",      {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_crystals_placer",       nil, true, nil, nil, atlas, "reno_lamp_crystals.tex")
AddRecipe("deco_lamp_upturn",        {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_upturn_placer",         nil, true, nil, nil, atlas, "reno_lamp_upturn.tex")
AddRecipe("deco_lamp_2upturns",      {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_2upturns_placer",       nil, true, nil, nil, atlas, "reno_lamp_2upturns.tex")
AddRecipe("deco_lamp_spool",         {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_spool_placer",          nil, true, nil, nil, atlas, "reno_lamp_spool.tex")
AddRecipe("deco_lamp_edison",        {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_edison_placer",         nil, true, nil, nil, atlas, "reno_lamp_edison.tex")
AddRecipe("deco_lamp_adjustable",    {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_adjustable_placer",     nil, true, nil, nil, atlas, "reno_lamp_adjustable.tex")
AddRecipe("deco_lamp_rightangles",   {Ingredient("goldnugget",8)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_rightangles_placer",    nil, true, nil, nil, atlas, "reno_lamp_rightangles.tex")
AddRecipe("deco_lamp_hoofspa",        {Ingredient("goldnugget",8)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_lamp_hoofspa_placer",        nil, true, nil, nil, atlas, "reno_lamp_hoofspa.tex")

AddRecipe("deco_plantholder_basic",        {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_basic_placer",           nil, true, nil, nil, atlas, "reno_plantholder_basic.tex")
AddRecipe("deco_plantholder_wip",          {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_wip_placer",             nil, true, nil, nil, atlas, "reno_plantholder_wip.tex")
AddRecipe("deco_plantholder_marble",        {Ingredient("goldnugget",6)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_marble_placer",          nil, true, nil, nil, atlas, "reno_plantholder_marble.tex")
AddRecipe("deco_plantholder_bonsai",       {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_bonsai_placer",          nil, true, nil, nil, atlas, "reno_plantholder_bonsai.tex")
AddRecipe("deco_plantholder_dishgarden",   {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_dishgarden_placer",      nil, true, nil, nil, atlas, "reno_plantholder_dishgarden.tex")
AddRecipe("deco_plantholder_philodendron", {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_philodendron_placer",    nil, true, nil, nil, atlas, "reno_plantholder_philodendron.tex")
AddRecipe("deco_plantholder_orchid",       {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_orchid_placer",          nil, true, nil, nil, atlas, "reno_plantholder_orchid.tex")
AddRecipe("deco_plantholder_draceana",     {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_draceana_placer",        nil, true, nil, nil, atlas, "reno_plantholder_draceana.tex")
AddRecipe("deco_plantholder_xerographica", {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_xerographica_placer",    nil, true, nil, nil, atlas, "reno_plantholder_xerographica.tex")
AddRecipe("deco_plantholder_birdcage",     {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_birdcage_placer",        nil, true, nil, nil, atlas, "reno_plantholder_birdcage.tex")
AddRecipe("deco_plantholder_palm",         {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_palm_placer",            nil, true, nil, nil, atlas, "reno_plantholder_palm.tex")
AddRecipe("deco_plantholder_zz",           {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_zz_placer",              nil, true, nil, nil, atlas, "reno_plantholder_zz.tex")
AddRecipe("deco_plantholder_fernstand",    {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_fernstand_placer",       nil, true, nil, nil, atlas, "reno_plantholder_fernstand.tex")
AddRecipe("deco_plantholder_fern",         {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_fern_placer",            nil, true, nil, nil, atlas, "reno_plantholder_fern.tex")
AddRecipe("deco_plantholder_terrarium",    {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_terrarium_placer",       nil, true, nil, nil, atlas, "reno_plantholder_terrarium.tex")
AddRecipe("deco_plantholder_plantpet",     {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_plantpet_placer",        nil, true, nil, nil, atlas, "reno_plantholder_plantpet.tex")
AddRecipe("deco_plantholder_traps",        {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_traps_placer",           nil, true, nil, nil, atlas, "reno_plantholder_traps.tex")
AddRecipe("deco_plantholder_pitchers",     {Ingredient("goldnugget",6)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_pitchers_placer",        nil, true, nil, nil, atlas, "reno_plantholder_pitchers.tex")


AddRecipe("deco_plantholder_winterfeasttreeofsadness",      {Ingredient("goldnugget",2),Ingredient("goldnugget",1)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_winterfeasttreeofsadness_placer", nil, true, nil, nil, atlas, "reno_plantholder_winterfeasttreeofsadness.tex")
AddRecipe("deco_plantholder_winterfeasttree",              {Ingredient("goldnugget",50)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_plantholder_winterfeasttree_placer",            nil, true, nil, nil, atlas, "reno_lamp_festivetree.tex") 

AddRecipe("deco_table_round",           {Ingredient("goldnugget",2)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_table_round_placer",    nil, true, nil, nil, atlas, "reno_table_round.tex")
AddRecipe("deco_table_banker",          {Ingredient("goldnugget",4)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_table_banker_placer",   nil, true, nil, nil, atlas, "reno_table_banker.tex")
AddRecipe("deco_table_diy",             {Ingredient("goldnugget",3)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_table_diy_placer",      nil, true, nil, nil, atlas, "reno_table_diy.tex")
AddRecipe("deco_table_raw",             {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_table_raw_placer",      nil, true, nil, nil, atlas, "reno_table_raw.tex")
AddRecipe("deco_table_crate",           {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_table_crate_placer",    nil, true, nil, nil, atlas, "reno_table_crate.tex")
AddRecipe("deco_table_chess",           {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_table_chess_placer",    nil, true, nil, nil, atlas, "reno_table_chess.tex")

AddRecipe("deco_wallornament_photo",                {Ingredient("goldnugget",2)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_photo_placer",               nil, true, nil, nil, atlas, "reno_wallornament_photo.tex")
AddRecipe("deco_wallornament_embroidery_hoop",      {Ingredient("goldnugget",3)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_embroidery_hoop_placer",     nil, true, nil, nil, atlas, "reno_wallornament_embroidery_hoop.tex")
AddRecipe("deco_wallornament_mosaic",               {Ingredient("goldnugget",4)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_mosaic_placer",              nil, true, nil, nil, atlas, "reno_wallornament_mosaic.tex")
AddRecipe("deco_wallornament_wreath",               {Ingredient("goldnugget",4)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_wreath_placer",              nil, true, nil, nil, atlas, "reno_wallornament_wreath.tex")
AddRecipe("deco_wallornament_axe",                  {Ingredient("goldnugget",5),  Ingredient("axe",1)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_axe_placer",                 nil, true, nil, nil, atlas, "reno_wallornament_axe.tex")
AddRecipe("deco_wallornament_hunt",                 {Ingredient("goldnugget",5),  Ingredient("spear",1)}, GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_hunt_placer",                nil, true, nil, nil, atlas, "reno_wallornament_hunt.tex")
AddRecipe("deco_wallornament_periodic_table",       {Ingredient("goldnugget",5)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_periodic_table_placer",      nil, true, nil, nil, atlas, "reno_wallornament_periodic_table.tex")
AddRecipe("deco_wallornament_gears_art",            {Ingredient("goldnugget",8)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_gears_art_placer",           nil, true, nil, nil, atlas, "reno_wallornament_gears_art.tex")
AddRecipe("deco_wallornament_cape",                 {Ingredient("goldnugget",5)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_cape_placer",                nil, true, nil, nil, atlas, "reno_wallornament_cape.tex")
AddRecipe("deco_wallornament_no_smoking",           {Ingredient("goldnugget",3)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_no_smoking_placer",          nil, true, nil, nil, atlas, "reno_wallornament_no_smoking.tex")
AddRecipe("deco_wallornament_black_cat",            {Ingredient("goldnugget",5)},                         GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wallornament_black_cat_placer",           nil, true, nil, nil, atlas, "reno_wallornament_black_cat.tex")
AddRecipe("deco_antiquities_wallfish",              {Ingredient("goldnugget",2),  Ingredient("fish",1)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_antiquities_wallfish_placer",             nil, true, nil, nil, atlas, "reno_antiquities_wallfish.tex")
AddRecipe("deco_antiquities_beefalo",               {Ingredient("goldnugget",10), Ingredient("horn",1)},  GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_antiquities_beefalo_placer",              nil, true, nil, nil, atlas, "reno_antiquities_beefalo.tex")

AddRecipe("window_small_peaked_curtain",        {Ingredient("goldnugget",3)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "window_small_peaked_curtain_placer",    nil, true, nil, nil, atlas, "reno_window_small_peaked_curtain.tex")
AddRecipe("window_round_burlap",                {Ingredient("goldnugget",3)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "window_round_burlap_placer",            nil, true, nil, nil, atlas, "reno_window_round_burlap.tex")
AddRecipe("window_small_peaked",                {Ingredient("goldnugget",3)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "window_small_peaked_placer",            nil, true, nil, nil, atlas, "reno_window_small_peaked.tex")
AddRecipe("window_large_square",                {Ingredient("goldnugget",4)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "window_large_square_placer",            nil, true, nil, nil, atlas, "reno_window_large_square.tex")
AddRecipe("window_tall",                        {Ingredient("goldnugget",4)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "window_tall_placer",                    nil, true, nil, nil, atlas, "reno_window_tall.tex")
AddRecipe("window_large_square_curtain",        {Ingredient("goldnugget",5)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "window_large_square_curtain_placer",    nil, true, nil, nil, atlas, "reno_window_large_square_curtain.tex")
AddRecipe("window_tall_curtain",                {Ingredient("goldnugget",5)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "window_tall_curtain_placer",            nil, true, nil, nil, atlas, "reno_window_tall_curtain.tex")

AddRecipe("window_greenhouse",                  {Ingredient("goldnugget",8)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "window_greenhouse_placer",          nil, true, nil, nil, atlas, "reno_window_greenhouse.tex")

AddRecipe("deco_wood",                          {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_wood_cornerbeam_placer",       nil, true, nil, nil, atlas, "reno_cornerbeam_wood.tex")
AddRecipe("deco_millinery",                     {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_millinery_cornerbeam_placer",  nil, true, nil, nil, atlas, "reno_cornerbeam_millinery.tex")
AddRecipe("deco_round",                         {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_round_cornerbeam_placer",      nil, true, nil, nil, atlas, "reno_cornerbeam_round.tex")
AddRecipe("deco_marble",                        {Ingredient("goldnugget",5)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "deco_marble_cornerbeam_placer",     nil, true, nil, nil, atlas, "reno_cornerbeam_marble.tex")

AddRecipe("interior_floor_wood",                {Ingredient("goldnugget",5)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_marble",              {Ingredient("goldnugget",15)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_check",               {Ingredient("goldnugget",7)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_plaid_tile",          {Ingredient("goldnugget",10)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_sheet_metal",         {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
--[[ we dont have the anim for these                                                                                                                                                     
-- AddRecipe("interior_floor_gardenstone",         {Ingredient("goldnugget",10)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
-- AddRecipe("interior_floor_geometrictiles",      {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
-- AddRecipe("interior_floor_shag_carpet",         {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
-- AddRecipe("interior_floor_transitional",        {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
-- AddRecipe("interior_floor_woodpanels",          {Ingredient("goldnugget",10)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
--]]
AddRecipe("interior_floor_herringbone",         {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_hexagon",             {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_hoof_curvy",          {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_floor_octagon",             {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
                                                                                                                                                     
AddRecipe("interior_wall_wood",                 {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_checkered",            {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_floral",               {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_sunflower",            {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_harlequin",            {Ingredient("goldnugget",10)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
--[[ we dont have the anim for these                                                                                                                                                   
AddRecipe("interior_wall_peagawk",              {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_plain_ds",             {Ingredient("goldnugget",4)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_plain_rog",            {Ingredient("goldnugget",4)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_rope",                 {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
--]]
AddRecipe("interior_wall_circles",              {Ingredient("goldnugget",10)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_marble",               {Ingredient("goldnugget",15)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_mayorsoffice",         {Ingredient("goldnugget",15)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_fullwall_moulding",    {Ingredient("goldnugget",15)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("interior_wall_upholstered",          {Ingredient("goldnugget",8)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)

AddRecipe("swinging_light_basic_bulb",          {Ingredient("goldnugget",5)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_basic_bulb_placer",            nil, true, nil, nil, atlas, "reno_light_basic_bulb.tex")
AddRecipe("swinging_light_basic_metal",         {Ingredient("goldnugget",6)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_basic_metal_placer",           nil, true, nil, nil, atlas, "reno_light_basic_metal.tex")
AddRecipe("swinging_light_chandalier_candles",  {Ingredient("goldnugget",8)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_chandalier_candles_placer",    nil, true, nil, nil, atlas, "reno_light_chandalier_candles.tex")
AddRecipe("swinging_light_rope_1",              {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_rope_1_placer",                nil, true, nil, nil, atlas, "reno_light_rope_1.tex")
AddRecipe("swinging_light_rope_2",              {Ingredient("goldnugget",1)},     GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_rope_2_placer",                nil, true, nil, nil, atlas, "reno_light_rope_2.tex")
AddRecipe("swinging_light_floral_bulb",         {Ingredient("goldnugget",10)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_floral_bulb_placer",           nil, true, nil, nil, atlas, "reno_light_floral_bulb.tex")
AddRecipe("swinging_light_pendant_cherries",    {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_pendant_cherries_placer",      nil, true, nil, nil, atlas, "reno_light_pendant_cherries.tex")
AddRecipe("swinging_light_floral_scallop",      {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_floral_scallop_placer",        nil, true, nil, nil, atlas, "reno_light_floral_scallop.tex")
AddRecipe("swinging_light_floral_bloomer",      {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_floral_bloomer_placer",        nil, true, nil, nil, atlas, "reno_light_floral_bloomer.tex")
AddRecipe("swinging_light_tophat",              {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_tophat_placer",                nil, true, nil, nil, atlas, "reno_light_tophat.tex")
AddRecipe("swinging_light_derby",               {Ingredient("goldnugget",12)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "swinging_light_derby_placer",                 nil, true, nil, nil, atlas, "reno_light_derby.tex")

-- DOORS
        --name,         ingredients,                tab,                    level,          game_type,                  placer,       min_spacing, nounlock, numtogive, aquatic, distance, decor, flipable, image, wallitem
AddRecipe("wood_door",      {Ingredient("goldnugget", 10)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "wood_door_placer",    nil, true, nil, nil, atlas, "wood_door.tex")
AddRecipe("stone_door",     {Ingredient("goldnugget", 10)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "stone_door_placer",   nil, true, nil, nil, atlas, "stone_door.tex")
AddRecipe("organic_door",   {Ingredient("goldnugget", 15)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "organic_door_placer", nil, true, nil, nil, atlas, "organic_door.tex")
AddRecipe("iron_door",      {Ingredient("goldnugget", 15)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "iron_door_placer",    nil, true, nil, nil, atlas, "iron_door.tex")
AddRecipe("curtain_door",   {Ingredient("goldnugget", 15)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "curtain_door_placer", nil, true, nil, nil, atlas, "curtain_door.tex")
AddRecipe("plate_door",     {Ingredient("goldnugget", 15)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "plate_door_placer",   nil, true, nil, nil, atlas, "plate_door.tex")
AddRecipe("round_door",     {Ingredient("goldnugget", 20)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "round_door_placer",   nil, true, nil, nil, atlas, "round_door.tex")
AddRecipe("pillar_door",    {Ingredient("goldnugget", 20)},   GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, "pillar_door_placer",  nil, true, nil, nil, atlas, "pillar_door.tex")

AddRecipe("construction_permit",   {Ingredient("goldnugget", 50)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
AddRecipe("demolition_permit",     {Ingredient("goldnugget", 10)},    GLOBAL.CUSTOM_RECIPETABS.RenovateTab, GLOBAL.TECH.SCIENCE_ONE, nil, nil, true,nil,nil,atlas)
